export const normalTheme = {
  borderRadiusLarge: '8px',
  borderRadiusMedium: '4px',

  colors: {
    white: '#fff',
    black: '#000',

    textPrimaryColor: '#1A1A1A',
    textSecondaryColor: '#A3A3A3',

    inputBackgroundColor: '#E8F0FE',
    borderGrayColor: '#ECECEC',
    borderParam: '#f0f0f0',
    backgroundGrayOne: '#F9F9FB',
    bluePrimary: '#1574F6',
    tealPrimary: '#9BE6F8',
    tealSecondary: '#54BBD8',
    orangePrimary: '#EF4123',
    blueSecondary: '#448AFF',
    blueTertiary: '#40A9FF',
    yellowPrimary: '#F2C94C',
    greyPrimary: '#828282',
    greySecondary: '#9f9fa0',
    greenPrimary: '#27AE60',
    violetPrimary: '#9B51E0',
    cyanPrimary: '#24B8CC',
    redPrimary: '#EB5757',
    borderDefault: '#CED4DA',
    borderBoldDefault: '#868E96',
    davyGrey: '#5C5C5D',
    pinkPrimary: '#F5126F',
  },

  fontSizes: {
    small: '12px',
    normal: '14px',
    regular: '16px',
    header: '17px',
    semiLarge: '18px',
    large: '20px',
    xLarge: '22px',
  },

  fontWeight: {
    light: '300',
    regular: '400',
    medium: '500',
    bold: '700',
    superBold: '900',
  },
  background: {
    primary: '#FFFFFF',
    second: '#ecebeb',
    menu: '#FFFFFF',
    third: '#FFFFFF',
    hoverMenu: '#F5F5F5',
    hoverRowTable: '#fafafa',
    activeRowTable: '#bae7ff',
    switch: '#bfbfbf',
    pagination: '#F44336',
    disableInput: '#f5f5f5',
    dropdownSelect: '',
    primaryBt: '#fff',
    emptyTable: '#19141B',
  },
  textColor: {
    bold: 'black',
    primary: '#1A1A1A',
    advanceSearch: '#2e7ce8',
    highlight: '#54BBD8',
    menuLink: '#8e8e8e',
    disableInput: 'rgba(0, 0, 0, 0.25)',
    second: '#F34223',
    primaryBt: '#F34223',
    titleSearch: '#606060',
    notifyName: '#1A1A1A',
  },
  border: {
    primary: '#ebebeb',
    modal: '#f0f0f0',
    primaryBt: '#borderDefault',
    input: '#d9d9d9',
  },
  menu: {
    textColor: {
      primary: '#5E5E5E',
    },
  },
};
